Gab masoud
kyweez/CDA-15-APPLICATION-DESIGN pull request #35
Opened 2021-02-21 10:45 UTC by kyweez

2021-02-21 11:27 UTC, SylvainTorrenti requested changes
Est-il possible d'avoir les aperçu (image et pdf) pour facilité la vision merci :).

2021-02-21 12:33 UTC, kyweez commented
Il va s'en occuper ce soir je crois, il est pas dispo cet après-midi je crois. Demain, j'ai mis un rdv pour 8h30 pour qu'on mette un peu en commun notre travail

2021-02-21 12:37 UTC, SylvainTorrenti commented
De toute façon c'est pas urgent on est dimanche :)

2021-02-22 07:10 UTC, kyweez commented
Le diagramme de navigabilité est en fait un diagramme d'activité, selon moi

2021-02-22 07:12 UTC, SylvainTorrenti commented
Pour moi aussi je ne savais pas trop comment l'amener et je pensais en discuter pendant notre réunion ce matin

2021-02-24 08:06 UTC, merged